# Generated by Django 4.0.1 on 2023-08-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deleted',
        ),
    ]
